language: ruby
rvm:
  - 2.2
  - 2.0.0
  - 2.1
  - jruby-9000
script: "rake spec:all"
before_install:
 - sudo apt-get update
 - sudo apt-get install idn
 - gem install bundler
notifications:
  email:
    recipients:
      - sbazyl@google.com
    on_success: change
    on_failure: change
